Listen 443

<VirtualHost *:443>
    ServerName koji-hub

    SSLEngine on
    SSLCertificateFile /etc/pki/koji/kojihub.crt
    SSLCertificateKeyFile /etc/pki/koji/kojihub.key
    SSLCACertificateFile /etc/pki/koji/koji_ca_cert.crt
    SSLVerifyClient optional
    SSLVerifyDepth 10
    SSLOptions +StdEnvVars +ExportCertData

    # Koji Hub XMLRPC
    WSGIDaemonProcess kojihub user=apache group=apache processes=2 threads=4
    WSGIProcessGroup kojihub
    WSGIPassAuthorization On
    Alias /kojihub /usr/share/koji-hub/kojiapp.py
    <Directory /usr/share/koji-hub>
        Options ExecCGI
        SetHandler wsgi-script
        WSGIApplicationGroup %{GLOBAL}
        SSLOptions +StdEnvVars +ExportCertData
        Require all granted
    </Directory>

    # Koji Web
    Alias /koji /usr/share/koji-web/scripts/wsgi_publisher.py
    <Directory /usr/share/koji-web/scripts>
        Options ExecCGI
        SetHandler wsgi-script
        WSGIApplicationGroup %{GLOBAL}
        Require all granted
    </Directory>

    # Koji Files
    Alias /kojifiles /mnt/koji
    <Directory /mnt/koji>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>
</VirtualHost>
