[hub]
DBName = koji
DBUser = koji
DBHost = db
DBPass = kojisecret

KojiDir = /mnt/koji

AuthPrincipal = kojihub

DNUsernameComponent = CN
ProxyDNs = /C=US/ST=Local/L=Local/O=Koji/OU=kojiweb/CN=koji-web

LoginCreatesUser = On
KojiWebURL = https://koji-hub/koji
