[web]
SiteName = Local Koji
KojiHubURL = https://localhost/kojihub
KojiFilesURL = https://localhost/kojifiles

WebCert = /etc/pki/koji/kojiweb.pem
ClientCA = /etc/pki/koji/koji_ca_cert.crt
KojiHubCA = /etc/pki/koji/koji_ca_cert.crt

LoginTimeout = 72
Secret = kojisecretkey
